# Generated by Django 3.0.5 on 2020-05-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='other_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_account',
        ),
    ]
