# Generated by Django 3.0.5 on 2020-06-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20200606_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('done', 'Done'), ('failed', 'Failed'), ('cancel', 'Cancel')], default='draft', max_length=50),
        ),
    ]
