# Generated by Django 3.0.5 on 2020-06-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='keyword',
            field=models.TextField(blank=True),
        ),
    ]
