# Generated by Django 3.0.5 on 2020-04-26 09:19

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'currencies')


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    Currency = apps.get_model("currency", "Currency")
    Currency.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0002_auto_20200426_0919'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
