# Generated by Django 3.0.5 on 2020-05-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='scale',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
