# Generated by Django 3.0.5 on 2020-05-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_load_currencies'),
        ('currency_rate', '0002_currencyrate_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency', unique=True),
        ),
    ]
