# Generated by Django 3.0.5 on 2020-04-26 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number_account', models.CharField(max_length=35)),
                ('number_card', models.CharField(max_length=35)),
                ('type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('opening_debit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('opening_credit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('category', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Card', 'Card'), ('Monybox', 'Monybox'), ('Deposit', 'Deposit')], max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
