# Generated by Django 3.0.5 on 2020-05-09 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_account', '0003_auto_20200509_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='number_account',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='number_card',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
