# Generated by Django 3.0.5 on 2020-05-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0004_auto_20200509_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='opening_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='opening_debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19),
        ),
    ]
