# Generated by Django 3.0.5 on 2020-05-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0006_auto_20200516_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_account.BankAccount')),
            ],
        ),
    ]
